config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#index'
  
  get 'pages/nosotros'

  get 'pages/faqs'

  get 'pages/tyc'

  get 'pages/contacto'
  
  get 'pages/signin'
  
  get 'pages/signup'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #------------------------------------------
  #------ utilizar nuevo layout excepto index
  

  layout "home_layout", only: [:index]
  
  def index
  end
  
  def nosotros
  end

  def faqs
  end

  def tyc
  end

  def contacto
  end
  
  def signin
  end
  
  def signup
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_menu.html.erb
<li><%= link_to "Nosotros", pages_nosotros_path  %></li>

<li><%= link_to "FAQ", pages_faqs_path  %></li>

<li><%= link_to "Términos y Condiciones", pages_tyc_path  %></li>

<li><%= link_to "Contacto", pages_contacto_path  %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Instaparking" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">Instaparking-croloncho</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="containercccc">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/home_layout.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Instaparking" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    

  </head>
  <body>
    
    <!-- Menu Principal -->
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">InstaParking</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <%= render 'layouts/menu' %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Iniciar sesión", pages_signin_path  %></a></li>
            <li><%= link_to "Registro", pages_signup_path  %></a></li>
          </ul>
        </div>
      </div>
    </div>
    <!-- /Menu Principal -->
    
    <!-- Container -->
    <div class="container_main container">
        <%= bootstrap_flash %>
        <%= yield %>
    </div>
    <!-- /Container -->
    
    <!-- Pie de Página -->
    <footer class="footer">
      <div class="container">
          <div class="row">
              <div class="col-md-12">
                  <ul class="nav navbar-nav navbar-left">
                    <%= render 'layouts/menu' %>
                  </ul>
                  <ul class="nav navbar-nav navbar-right">
                    <li><p>Todos los derechos reservados</p></li>
                  </ul>
              </div>
          </div>
      </div>
    </footer>
    <!-- /Pie de Página -->
    
  </body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instaparking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/contacto.html.erb
<div class="row row-centered block_contacto">
    
    <h2>Contáctanos</h2>
    
    <div class="col-lg-2 panel_contacto" style="text-align:left">
        <form>
          <div class="form-group">
            <label for="exampleInputEmail1">Nombres y Apellidos</label>
            <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Ingrese sus Nombres y Apellidos">
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Correo electrónico</label>
            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Ingrese su correo electrónico">
          </div>
          <div class="form-group">
            <label for="exampleInputFile">Comentario</label>
            <textarea class="form-control" placeholder="Ingresa su comentario"></textarea>
          </div>
          
          <button type="submit" class="btn btn-default">Enviar</button>
        </form>
    </div>
</div>

app/views/pages/faqs.html.erb
<h1>
    <p class="text-center">FAQs</p>
</h1>

<h2>FREQUENTLY ASKED QUESTIONS</h2>

<p>Are there any additional fees onsite?</p>
<p>Can a reservation be cancelled?</p>
<p>Can I book a spot for someone else?</p>
<p>Can I book a spot over the phone?</p>
<p>Can I book more than one parking spot at a time?</p>
<p>Can I make a monthly reservation for only one month?</p>
<p>Can I redeem my reservation without cell service?</p>
<p>Can I reserve handicapped parking?</p>
<p>Can I sell my passes on another website?</p>
<p>Can I show my parking pass on my phone?</p>
<p>Can I show my parking pass on my phone?</p>
<p>Do I have to enter a vehicle description? What if I don’t know it?</p>
<p>Do I have to have the app to use my mobile confirmation?</p>
<p>Do I have to make a new reservation each month?</p>
<p>Do I need to create an account in order to book a reservation?</p>

app/views/pages/index.html.erb
<!-- Buscador  -->
<div class="row row-centered block_buscador">
  <div class="col-lg-12">
    <h2>Busca tu espacio</h2>
    <p>Obten promociones y descuentos</p>
    <form class="form-inline form_buscador">
      <div class="form-group">
        <input class="form-control input_buscador">
        <button class="btn btn-default">Buscar</button>  
      </div>
    </form>
    
  </div>
</div>
<!-- / Buscador  -->

<!-- Slider  -->
<div class="row row-centered block_slider">
  
  <h2>Nuestros<br>Establecimientos</h2>
  
  <div class="col-sm-5 slider">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>
    
      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <%= image_tag "estacion1.jpg", html: { alt: "estacion 1" } %>
          <div class="carousel-caption">
            Imagen 1
          </div>
        </div>
        <div class="item">
          <%= image_tag "estacion2.jpg", html: { alt: "estacion 2" } %>
          <div class="carousel-caption">
            Imagen 2
          </div>
        </div>
        <div class="item">
          <%= image_tag "estacion3.jpg", html: { alt: "estacion 3" } %>
          <div class="carousel-caption">
            Imagen 3
          </div>
        </div>
      </div>
    
      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

  </div>
</div>
<!-- /Slider  -->

<!-- Servicios -->
<div class="row block_servicios">
  <div class="col-lg-12">
    <h2>Nuestros Servicios</h2>
  </div>
  <div class="col-sm-6 col-md-6 block_servicio_1">
       <%= image_tag "estacion4.jpg", html: { alt: "reserva" } %>
      <div class="caption">
        <h3>Reservar tu espacio</h3>
        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. <br>Donec id elit non mi porta gravida at eget metus. Nullam id dolor <br>id nibh ultricies vehicula ut id elit.Button</p>
        <p><a href="#" class="btn btn-default" role="button">Ver más</a></p>
      </div>
  </div>

  <div class="col-sm-6 col-md-6 block_servicio_2">
      <%= image_tag "mapa.jpg", html: { alt: "oferta" } %>
      <div class="caption">
        <h3>Ofertar tu espacio</h3>
        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. <br>Donec id elit non mi porta gravida at eget metus. Nullam id dolor <br>id nibh ultricies vehicula ut id elit.Button</p>
        <p><a href="#" class="btn btn-default" role="button">Ver más</a></p>
      </div>
  </div>
</div>
<!-- /Servicios -->

app/views/pages/nosotros.html.erb
<h1><p class="text-center">Nosotros</p></h1>
<p class="text-center">Lorem ipsum dolor sit amet, sapien etiam, nunc amet dolor ac odio mauris justo. Luctus arcu, urna praesent at id quisque ac. Arcu es massa vestibulum malesuada, integer vivamus elit eu mauris eus, cum eros quis aliquam wisi. Nulla wisi laoreet suspendisse integer vivamus elit eu mauris hendrerit facilisi, mi mattis pariatur aliquam pharetra eget Lorem ipsum dolor sit amet, sapien etiam, nunc amet dolor ac odio mauris justo. Luctus arcu, urna praesent at id quisque ac. Arcu es massa vestibulum malesuada, integer vivamus elit eu mauris eus, cum eros quis aliquam wisi. Nulla wisi laoreet suspendisse integer vivamus elit eu mauris hendrerit facilisi, mi mattis pariatur aliquam pharetra eget.
Lorem ipsum dolor sit amet, sapien etiam, nunc amet dolor ac odio mauris justo. Luctus arcu, urna praesent at id quisque ac. Arcu es massa vestibulum malesuada, integer vivamus elit eu mauris eus, cum eros quis aliquam wisi. Nulla wisi laoreet suspendisse integer vivamus elit eu mauris hendrerit facilisi, mi mattis pariatur aliquam pharetra eget.</p>

app/views/pages/signin.html.erb
<h1>Contactos</h1>

app/views/pages/signup.html.erb
<h1>Contactos</h1>

app/views/pages/tyc.html.erb
<h1>Terminos y Condiciones</h1>



<p1>La página web de instaparking ( "el Sitio") es una agencia de alquiler de espacio de estacionamiento que le permite reservar plazas de aparcamiento en cualquier parte del mundo.</p1>

<p2>El sitio es operado por JustPark Limited ( "nosotros" o "nosotros") y la membresía está abierta a cualquier persona que opta por registrarse en el sitio.
Estas condiciones se aplicarán a cualquier persona que ve o utiliza el Sitio ( "usted").
Tanto si se registra o no quedará obligado por estos términos y condiciones en su totalidad y también se acepta que quedará vinculado por los términos de nuestra política de
privacidad que explica el uso que estamos autorizados para hacer de su información personal.
Estos términos y condiciones se relacionan con su uso pasivo del sitio, si desea reservar una plaza de aparcamiento a través del Sitio, usted también tendrá que entrar en un
acuerdo de licencia Plaza de estacionamiento con el propietario plaza de aparcamiento y que se consideran obligados por nuestro acuerdo Conductor .
Si usted es propietario de una plaza de aparcamiento y desea alquilar su plaza de aparcamiento con nosotros usted estará obligado por nuestra
Aparcamiento acuerdo sobre el Espacio propietario.
Tenga en cuenta que estos términos y condiciones pueden ser modificados de vez en cuando. La notificación de cualquier cambio se hará mediante la publicación de nuevos
términos en el Sitio. Al continuar utilizando el Sitio, usted confirma que acepta los términos y condiciones vigentes en ese momento en su totalidad en el momento de utilizar el Sitio.</p2>